CREATE TABLE `ApiFootballFreshOddsCheckpoint` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `providerFixtureId` INTEGER NOT NULL,
    `providerLeagueId` INTEGER NOT NULL,
    `season` INTEGER NOT NULL,
    `kickoffAt` DATETIME(3) NOT NULL,
    `horizonMinutes` INTEGER NOT NULL,
    `horizonLabel` VARCHAR(32) NOT NULL,
    `dueAt` DATETIME(3) NOT NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `attemptedAt` DATETIME(3) NULL,
    `completedAt` DATETIME(3) NULL,
    `nextRetryAt` DATETIME(3) NULL,
    `lockToken` VARCHAR(64) NULL,
    `requestCount` INTEGER NOT NULL DEFAULT 0,
    `normalizedOdds` INTEGER NOT NULL DEFAULT 0,
    `insertedOdds` INTEGER NOT NULL DEFAULT 0,
    `pitUsableOdds` INTEGER NOT NULL DEFAULT 0,
    `quotaRemainingDay` INTEGER NULL,
    `quotaRemainingMinute` INTEGER NULL,
    `errorMessage` TEXT NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ApiFootballFreshOddsCheckpoint_fixture_horizon_key`(`providerFixtureId`, `horizonMinutes`),
    INDEX `ApiFootballFreshOddsCheckpoint_status_due_idx`(`status`, `dueAt`),
    INDEX `ApiFootballFreshOddsCheckpoint_fixture_kickoff_idx`(`providerFixtureId`, `kickoffAt`),
    INDEX `ApiFootballFreshOddsCheckpoint_horizon_status_due_idx`(`horizonMinutes`, `status`, `dueAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
