CREATE TABLE `ScientificBankrollRiskPolicy` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `accountKey` VARCHAR(64) NOT NULL,
    `policyVersion` VARCHAR(160) NOT NULL,
    `stakingMode` VARCHAR(32) NOT NULL,
    `startingBankrollUnits` DOUBLE NOT NULL,
    `flatStakeUnits` DOUBLE NOT NULL,
    `kellyFraction` DOUBLE NOT NULL,
    `minimumStakeUnits` DOUBLE NOT NULL,
    `maximumStakeUnits` DOUBLE NOT NULL,
    `maximumStakeFraction` DOUBLE NOT NULL,
    `maximumOpenExposureFraction` DOUBLE NOT NULL,
    `maximumDailyExposureFraction` DOUBLE NOT NULL,
    `maximumLeagueExposureFraction` DOUBLE NOT NULL,
    `maximumDailyLossFraction` DOUBLE NOT NULL,
    `drawdownSoftLimit` DOUBLE NOT NULL,
    `drawdownHardLimit` DOUBLE NOT NULL,
    `minimumBankrollUnits` DOUBLE NOT NULL,
    `roundingUnits` DOUBLE NOT NULL,
    `configuration` JSON NOT NULL,
    `payloadHash` VARCHAR(64) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ScientificBankrollRiskPolicy_payloadHash_key`(`payloadHash`),
    INDEX `ScientificBankrollRiskPolicy_account_created_idx`(`accountKey`, `createdAt`),
    INDEX `ScientificBankrollRiskPolicy_version_created_idx`(`policyVersion`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ScientificPaperStakeDecision` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `riskPolicyId` INTEGER NOT NULL,
    `riskPolicyHash` VARCHAR(64) NOT NULL,
    `paperDecisionId` INTEGER NOT NULL,
    `paperDecisionHash` VARCHAR(64) NOT NULL,
    `providerFixtureId` INTEGER NOT NULL,
    `localFixtureId` INTEGER NULL,
    `leagueId` INTEGER NULL,
    `horizonMinutes` INTEGER NOT NULL,
    `decisionAsOf` DATETIME(3) NOT NULL,
    `evaluatedAt` DATETIME(3) NOT NULL,
    `kickoffAt` DATETIME(3) NOT NULL,
    `paperDecisionType` VARCHAR(16) NOT NULL,
    `stakeDecisionType` VARCHAR(16) NOT NULL,
    `stakingMode` VARCHAR(32) NOT NULL,
    `selectedMarket` VARCHAR(32) NULL,
    `selectedSelection` VARCHAR(24) NULL,
    `lineValue` DOUBLE NULL,
    `decimalOdds` DOUBLE NULL,
    `modelProbability` DOUBLE NULL,
    `fairMarketProbability` DOUBLE NULL,
    `edge` DOUBLE NULL,
    `expectedValue` DOUBLE NULL,
    `stakeUnits` DOUBLE NOT NULL,
    `stakeFraction` DOUBLE NOT NULL,
    `requestedStakeUnits` DOUBLE NOT NULL,
    `fullKellyFraction` DOUBLE NULL,
    `appliedKellyFraction` DOUBLE NULL,
    `drawdownMultiplier` DOUBLE NOT NULL,
    `riskBand` VARCHAR(24) NOT NULL,
    `bankrollBeforeUnits` DOUBLE NOT NULL,
    `peakBankrollBeforeUnits` DOUBLE NOT NULL,
    `openExposureBeforeUnits` DOUBLE NOT NULL,
    `dailyExposureBeforeUnits` DOUBLE NOT NULL,
    `leagueExposureBeforeUnits` DOUBLE NOT NULL,
    `dailyRealizedPnlBeforeUnits` DOUBLE NOT NULL,
    `drawdownBeforeFraction` DOUBLE NOT NULL,
    `riskReasons` JSON NOT NULL,
    `cappedBy` JSON NOT NULL,
    `calculationPayload` JSON NOT NULL,
    `stakeHash` VARCHAR(64) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ScientificPaperStakeDecision_stakeHash_key`(`stakeHash`),
    UNIQUE INDEX `ScientificPaperStakeDecision_policy_decision_key`(`riskPolicyId`, `paperDecisionId`),
    INDEX `ScientificPaperStakeDecision_policy_evaluated_idx`(`riskPolicyId`, `evaluatedAt`),
    INDEX `ScientificPaperStakeDecision_type_evaluated_idx`(`stakeDecisionType`, `evaluatedAt`),
    INDEX `ScientificPaperStakeDecision_fixture_horizon_idx`(`providerFixtureId`, `horizonMinutes`),
    INDEX `ScientificPaperStakeDecision_league_evaluated_idx`(`leagueId`, `evaluatedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ScientificBankrollStakeSettlement` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `riskPolicyId` INTEGER NOT NULL,
    `riskPolicyHash` VARCHAR(64) NOT NULL,
    `stakeDecisionId` INTEGER NOT NULL,
    `paperDecisionId` INTEGER NOT NULL,
    `paperSettlementId` INTEGER NOT NULL,
    `providerFixtureId` INTEGER NOT NULL,
    `settledAt` DATETIME(3) NOT NULL,
    `result` VARCHAR(16) NOT NULL,
    `stakeUnits` DOUBLE NOT NULL,
    `decimalOdds` DOUBLE NOT NULL,
    `profitUnits` DOUBLE NOT NULL,
    `bankrollBeforeUnits` DOUBLE NOT NULL,
    `bankrollAfterUnits` DOUBLE NOT NULL,
    `peakBankrollAfterUnits` DOUBLE NOT NULL,
    `drawdownAfterFraction` DOUBLE NOT NULL,
    `settlementPayload` JSON NOT NULL,
    `settlementHash` VARCHAR(64) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ScientificBankrollStakeSettlement_stakeDecisionId_key`(`stakeDecisionId`),
    UNIQUE INDEX `ScientificBankrollStakeSettlement_settlementHash_key`(`settlementHash`),
    UNIQUE INDEX `ScientificBankrollStakeSettlement_policy_paper_key`(`riskPolicyId`, `paperSettlementId`),
    INDEX `ScientificBankrollStakeSettlement_policy_settled_idx`(`riskPolicyId`, `settledAt`),
    INDEX `ScientificBankrollStakeSettlement_result_settled_idx`(`result`, `settledAt`),
    INDEX `ScientificBankrollStakeSettlement_fixture_settled_idx`(`providerFixtureId`, `settledAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
