CREATE TABLE `ScientificCurrentSignalSnapshot` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `providerFixtureId` INTEGER NOT NULL,
    `localFixtureId` INTEGER NULL,
    `checkpointMinutes` INTEGER NOT NULL,
    `checkpointLabel` VARCHAR(24) NOT NULL,
    `actualHorizonMinutes` INTEGER NOT NULL,
    `snapshotAsOf` DATETIME(3) NOT NULL,
    `kickoffAt` DATETIME(3) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `selectedMarket` VARCHAR(32) NULL,
    `selectedSelection` VARCHAR(24) NULL,
    `lineValue` DOUBLE NULL,
    `decimalOdds` DOUBLE NULL,
    `bookmakerName` VARCHAR(160) NULL,
    `modelProbability` DOUBLE NULL,
    `fairMarketProbability` DOUBLE NULL,
    `impliedProbability` DOUBLE NULL,
    `edge` DOUBLE NULL,
    `expectedValue` DOUBLE NULL,
    `reliabilityStatus` VARCHAR(96) NULL,
    `modelSource` VARCHAR(64) NULL,
    `modelFallbackReason` VARCHAR(128) NULL,
    `modelConfidenceTier` VARCHAR(16) NULL,
    `modelHistorySampleSize` INTEGER NULL,
    `dataQualityScore` DOUBLE NULL,
    `modelVersion` TEXT NULL,
    `sourceOddsSnapshotId` INTEGER NULL,
    `sourceOddsUpdatedAt` DATETIME(3) NULL,
    `sourceOddsFirstObservedAt` DATETIME(3) NULL,
    `sourceOddsReobservedAt` DATETIME(3) NULL,
    `sourceOddsFreshnessAt` DATETIME(3) NULL,
    `oddsFreshnessBasis` VARCHAR(32) NULL,
    `reobservationRawSnapshotId` INTEGER NULL,
    `latestLineupCapturedAt` DATETIME(3) NULL,
    `latestInjuryCapturedAt` DATETIME(3) NULL,
    `candidateCount` INTEGER NOT NULL DEFAULT 0,
    `currentEligibleCandidateCount` INTEGER NOT NULL DEFAULT 0,
    `officialEligibleCandidateCount` INTEGER NOT NULL DEFAULT 0,
    `analysisPayload` JSON NOT NULL,
    `snapshotHash` VARCHAR(64) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ScientificCurrentSignalSnapshot_snapshotHash_key`(`snapshotHash`),
    UNIQUE INDEX `ScientificCurrentSignal_fixture_checkpoint_key`(`providerFixtureId`, `checkpointMinutes`),
    INDEX `ScientificCurrentSignal_fixture_asof_idx`(`providerFixtureId`, `snapshotAsOf`),
    INDEX `ScientificCurrentSignal_checkpoint_asof_idx`(`checkpointMinutes`, `snapshotAsOf`),
    INDEX `ScientificCurrentSignal_status_asof_idx`(`status`, `snapshotAsOf`),
    INDEX `ScientificCurrentSignal_market_selection_idx`(`selectedMarket`, `selectedSelection`),
    INDEX `ScientificCurrentSignal_model_source_idx`(`modelSource`, `snapshotAsOf`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
