-- Backtest persistence: one run stores its configuration and aggregate metrics;
-- each simulated recommendation is stored as an auditable point-in-time bet.

CREATE TABLE `BacktestRun` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `leagueId` INTEGER NULL,
  `dateFrom` DATETIME(3) NOT NULL,
  `dateTo` DATETIME(3) NOT NULL,
  `fixtureLimit` INTEGER NOT NULL,
  `stakeUnits` DOUBLE NOT NULL DEFAULT 1,
  `modelVersion` VARCHAR(191) NOT NULL,
  `rules` JSON NOT NULL,
  `status` ENUM('RUNNING','SUCCESS','FAILED') NOT NULL DEFAULT 'RUNNING',
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finishedAt` DATETIME(3) NULL,
  `totalFixtures` INTEGER NOT NULL DEFAULT 0,
  `eligibleFixtures` INTEGER NOT NULL DEFAULT 0,
  `totalBets` INTEGER NOT NULL DEFAULT 0,
  `wins` INTEGER NOT NULL DEFAULT 0,
  `losses` INTEGER NOT NULL DEFAULT 0,
  `pushes` INTEGER NOT NULL DEFAULT 0,
  `voids` INTEGER NOT NULL DEFAULT 0,
  `hitRate` DOUBLE NULL,
  `profitUnits` DOUBLE NOT NULL DEFAULT 0,
  `roi` DOUBLE NULL,
  `yieldRate` DOUBLE NULL,
  `averageOdds` DOUBLE NULL,
  `averageExpectedValue` DOUBLE NULL,
  `maximumDrawdown` DOUBLE NULL,
  `brierScore` DOUBLE NULL,
  `errorMessage` TEXT NULL,
  INDEX `BacktestRun_startedAt_idx` (`startedAt`),
  INDEX `BacktestRun_status_idx` (`status`),
  INDEX `BacktestRun_leagueId_dateFrom_dateTo_idx` (`leagueId`, `dateFrom`, `dateTo`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BacktestRun_leagueId_fkey` FOREIGN KEY (`leagueId`) REFERENCES `League` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `BacktestBet` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `runId` INTEGER NOT NULL,
  `fixtureId` INTEGER NOT NULL,
  `bookmakerId` INTEGER NOT NULL,
  `oddsSnapshotId` INTEGER NOT NULL,
  `predictedAt` DATETIME(3) NOT NULL,
  `kickoffAt` DATETIME(3) NOT NULL,
  `marketCode` VARCHAR(191) NOT NULL,
  `marketName` VARCHAR(191) NOT NULL,
  `marketGroup` VARCHAR(191) NOT NULL,
  `selectionCode` VARCHAR(191) NOT NULL,
  `selectionName` VARCHAR(191) NOT NULL,
  `lineValue` DOUBLE NULL,
  `decimalOdds` DOUBLE NOT NULL,
  `modelProbability` DOUBLE NOT NULL,
  `fairMarketProbability` DOUBLE NOT NULL,
  `edge` DOUBLE NOT NULL,
  `expectedValue` DOUBLE NOT NULL,
  `confidenceScore` DOUBLE NOT NULL,
  `dataQualityScore` DOUBLE NOT NULL,
  `recommendationScore` DOUBLE NOT NULL,
  `rankNumber` INTEGER NOT NULL,
  `settlementResult` ENUM('PENDING','WIN','LOSS','PUSH','VOID') NOT NULL,
  `stakeUnits` DOUBLE NOT NULL,
  `profitUnits` DOUBLE NOT NULL,
  `homeGoals` INTEGER NOT NULL,
  `awayGoals` INTEGER NOT NULL,
  `reasons` JSON NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `BacktestBet_runId_kickoffAt_idx` (`runId`, `kickoffAt`),
  INDEX `BacktestBet_marketCode_settlementResult_idx` (`marketCode`, `settlementResult`),
  INDEX `BacktestBet_fixtureId_idx` (`fixtureId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `BacktestBet_runId_fkey` FOREIGN KEY (`runId`) REFERENCES `BacktestRun` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BacktestBet_fixtureId_fkey` FOREIGN KEY (`fixtureId`) REFERENCES `Fixture` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `BacktestBet_bookmakerId_fkey` FOREIGN KEY (`bookmakerId`) REFERENCES `Bookmaker` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `BacktestBet_oddsSnapshotId_fkey` FOREIGN KEY (`oddsSnapshotId`) REFERENCES `OddsSnapshot` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
